#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

go fmt ./...

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

echo "$FILES" | xargs yarn format

yarn lint

exit 0
