name: Go

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v4
              with:
                  go-version: '1.21.x'

            - name: Install dependencies
              run: |
                  go mod download
                  go mod verify

            - name: Build
              run: |
                  mkdir bin
                  go build -v -o ./bin ./...

            - name: Test
              run: go test ./...
